[versions]
arrow = "18.3.0"
akka = "2.9.3"
akka-http = "10.6.3"

[libraries]
logback = { module = "ch.qos.logback:logback-classic", version = "1.5.23" }
sqlite = { module = "org.xerial:sqlite-jdbc", version = "3.51.1.0" }
jackson = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml", version = "2.20.0" }
arrow-dataset = { module = "org.apache.arrow:arrow-dataset", version.ref = "arrow" }
arrow-memory-netty = { module = "org.apache.arrow:arrow-memory-netty", version.ref = "arrow" }
akka-actor-typed = { module = "com.typesafe.akka:akka-actor-typed_3", version.ref = "akka" }
akka-stream = { module = "com.typesafe.akka:akka-stream_3", version.ref = "akka" }
akka-http = { module =  "com.typesafe.akka:akka-http_3", version.ref = "akka-http" }
akka-http-spray-json = { module = "com.typesafe.akka:akka-http-spray-json_3", version.ref = "akka-http" }
akka-actor-testkit-typed = { module = "com.typesafe.akka:akka-actor-testkit-typed_3", version.ref = "akka" }
akka-http-testkit = { module = "com.typesafe.akka:akka-http-testkit_3", version.ref = "akka-http" }

[bundles]
arrow = ["arrow-dataset", "arrow-memory-netty"]
akka = ["akka-actor-typed", "akka-stream", "akka-http", "akka-http-spray-json"]
akka-test = ["akka-actor-testkit-typed", "akka-http-testkit"]
